[meta]
name = "Record Ticker"
author = "MisfitMaid"
category = "Overlay"
version = "0.1"
siteid = 332

[script]
dependencies = ["NadeoServices"]
exports = [ "Export.Ticker.as" ]
shared_exports = [ "ExportShared.Ticker.as" ]
module = "ticker"
