[meta]
name = "Ticker"
author = "MisfitMaid"
category = "Overlay"
version = "0.2.3"
siteid = 332

[script]
exports = [ "Export.Ticker.as" ]
shared_exports = [ "ExportShared.Ticker.as" ]
module = "ticker"
